services:
  neo4j-seizures_apr2026:
    image: neo4j:latest
    container_name: neo4j-seizures-april2026
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - seizures_apr2026_data:/data
      - seizures_apr2026_logs:/logs
      - ./import/seizures_apr2026:/var/lib/neo4j/import
      - ./cypher/seizures_apr2026:/cypher

  neo4j-normal:
    image: neo4j:latest
    container_name: neo4j-normal
    ports