CREATE CONSTRAINT component_name IF NOT EXISTS
FOR (c:Component)
REQUIRE c.name IS UNIQUE;

CREATE CONSTRAINT region_name IF NOT EXISTS
FOR (r:Region)
REQUIRE r.name IS UNIQUE;

CREATE CONSTRAINT area_name IF NOT EXISTS
FOR (a:Area)
REQUIRE a.name IS UNIQUE;

CREATE CONSTRAINT drug_name IF NOT EXISTS
FOR (d:Drug)
REQUIRE d.name IS UNIQUE;